apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
    - Namespace
    - ResourceQuota
    - StorageClass
    - CustomResourceDefinition
    - MutatingWebhookConfiguration
    - ServiceAccount
    - PodSecurityPolicy
    - NetworkPolicy
    - Role
    - ClusterRole
    - RoleBinding
    - ClusterRoleBinding
    - ConfigMap
    - Secret
    - Endpoints
    - Service
    - LimitRange
    - PriorityClass
    - PersistentVolume
    - PersistentVolumeClaim
    - Deployment
    - StatefulSet
    - CronJob
    - PodDisruptionBudget
    orderLast:
    - ValidatingWebhookConfiguration

resources:
# Kubeflow Pipelines
- ../manifests/apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
# Katib
- ../manifests/apps/katib/upstream/installs/katib-with-kubeflow
# Central Dashboard
- ../manifests/apps/centraldashboard/overlays/oauth2-proxy
# Admission Webhook
- ../manifests/apps/admission-webhook/upstream/overlays/cert-manager
# Jupyter Web App
- ../manifests/apps/jupyter/jupyter-web-app/upstream/overlays/istio
# Notebook Controller
- ../manifests/apps/jupyter/notebook-controller/upstream/overlays/kubeflow
# Profiles + KFAM
- ../manifests/apps/profiles/upstream/overlays/kubeflow
# PVC Viewer
- ../manifests/apps/pvcviewer-controller/upstream/base
# Volumes Web App
- ../manifests/apps/volumes-web-app/upstream/overlays/istio
# Tensorboards Controller
- ../manifests/apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# Tensorboard Web App
- ../manifests/apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
# Training Operator
- ../manifests/apps/training-operator/upstream/overlays/kubeflow
# User namespace
- ../manifests/common/user-namespace/base

# KServe
- ../manifests/apps/kserve/kserve
- ../manifests/apps/kserve/models-web-app/overlays/kubeflow

# Ray is an experimental integration
# Here is the documentation for Ray: https://docs.ray.io/en/latest/
# Here is the internal documentation for Ray: - ../experimental/ray/README.md
# - ../experimental/ray/kuberay-operator/overlays/kubeflow

components:
# Pod Security Standards
# https://kubernetes.io/docs/concepts/security/pod-security-standards/
# Uncomment to enable baseline level standards
# - ../experimental/security/PSS/static/baseline
# Uncomment to enable restricted level standards
# - ../experimental/security/PSS/static/restricted
# Uncomment to enable baseline level standards for dynamic namespaces
# - ../experimental/security/PSS/dynamic/baseline
# Uncomment to enable restricted level standards for dynamic namespaces
# - ../experimental/security/PSS/dynamic/restricted
