apiVersion: kustomize.config.k8s.io/v1alpha1 
kind: Component

patches:
# - target:
#     group: networking.istio.io
#     version: v1
#     kind: Gateway
#     name: kubeflow-gateway
#   path: gateway.yaml

- target:
    version: v1
    kind: Service
    name: istio-ingressgateway
  path: service.yaml 